### ISSUE TITLE
React Native compatibility

### ISSUE THREAD

**Issue by davidtheclark** [mapbox/parse-mapbox-token#1]
@nitaliano tried this (via mapbox-sdk-js) in React Native, and neither of the available parsing methods were available:

![image](https://user-images.githubusercontent.com/628431/41071086-11f6bdcc-69ab-11e8-8056-fe10555c3c65.png)

@nitaliano You can see that we're just trying to decode base64: https://github.com/mapbox/parse-mapbox-token/blob/ec4888286d4d0b3593032d888e6366f1e82d9cc9/index.js#L37-L42 Do you know how we should do that so it works in React Native?

**Comment by nitaliano** [comment]
I think we have two options here

* We can implement a polyfill for `atob` and do something like
```
var atobImpl = (function () {
  if (typeof window !== 'undefined' && window.atob) {
     return window.atob;
  }
  
  return function atobPolyfill (payload) {
    // atob polyfill
  };
})();

if (typeof Buffer !== 'undefined') { 
   return JSON.parse(new Buffer(rawPayload, 'base64').toString()); 
}  else {
   return JSON.parse(atobImpl(rawPayload)); 
}
```

* We have our react native users inject `Buffer` into the global namespace before importing `mapbox-sdk-js` using https://github.com/feross/buffer

```
import Buffer from 'buffer';
global.Buffer = Buffer;
```
